"""shop table added

Revision ID: ffe902a27888
Revises: b60aa5d4250d
Create Date: 2025-04-30 02:48:40.352193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe902a27888'
down_revision: Union[str, None] = 'b60aa5d4250d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_id'), 'shops', ['id'], unique=False)
    op.create_index(op.f('ix_shops_owner_id'), 'shops', ['owner_id'], unique=False)
    op.create_index('uq_shops_name_active', 'shops', ['name'], unique=True, postgresql_where='deleted = false')
    op.create_index('uq_shops_slug_active', 'shops', ['slug'], unique=True, postgresql_where='deleted = false')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_shops_slug_active', table_name='shops', postgresql_where='deleted = false')
    op.drop_index('uq_shops_name_active', table_name='shops', postgresql_where='deleted = false')
    op.drop_index(op.f('ix_shops_owner_id'), table_name='shops')
    op.drop_index(op.f('ix_shops_id'), table_name='shops')
    op.drop_table('shops')
    # ### end Alembic commands ###
