"""roles added

Revision ID: fa6c591dbd6c
Revises: 9709bb2ceef5
Create Date: 2025-04-25 12:35:56.908776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa6c591dbd6c'
down_revision: Union[str, None] = '9709bb2ceef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

roles = ("owner", "admin", "seller", "customer")

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE role_enum AS ENUM %s" % str(tuple(roles)))
    op.add_column(
        'users',
                  sa.Column(
                      'role',
                      sa.Enum(*roles, name="role_enum"),
                      server_default='customer',
                      nullable=False
                  )
    )
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'role')
    op.execute("DROP TYPE role_enum")
    # ### end Alembic commands ###
