"""add deleted attribute for role_request table

Revision ID: 404c1d7977b3
Revises: 405c2da7fb0d
Create Date: 2025-05-05 19:57:09.437937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '404c1d7977b3'
down_revision: Union[str, None] = '405c2da7fb0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_requests', sa.Column('deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_requests', 'deleted')
    # ### end Alembic commands ###
