"""add cascade delete for role requests

Revision ID: 747b4c37d3b4
Revises: cc1dee83c056
Create Date: 2025-05-11 20:08:09.655087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747b4c37d3b4'
down_revision: Union[str, None] = 'cc1dee83c056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('role_requests_user_id_fkey', 'role_requests', type_='foreignkey')
    op.create_foreign_key(None, 'role_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_requests', type_='foreignkey')
    op.create_foreign_key('role_requests_user_id_fkey', 'role_requests', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
