"""delete tax attribute

Revision ID: b744e5c904ad
Revises: 6e63e1f7721d
Create Date: 2025-05-13 03:49:19.753003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b744e5c904ad'
down_revision: Union[str, None] = '6e63e1f7721d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'tax_snapshot')
    op.drop_column('orders', 'tax_total')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tax_total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('tax_snapshot', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
