"""add unique indexes for non deleted users

Revision ID: 66c9e6c74ba4
Revises: fa6c591dbd6c
Create Date: 2025-04-25 13:11:52.407584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c9e6c74ba4'
down_revision: Union[str, None] = 'fa6c591dbd6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_users_email_active', 'users', ['email'], unique=True, postgresql_where='deleted = false')
    op.create_index('uq_users_username_active', 'users', ['username'], unique=True, postgresql_where='deleted = false')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_username_active', table_name='users', postgresql_where='deleted = false')
    op.drop_index('uq_users_email_active', table_name='users', postgresql_where='deleted = false')
    # ### end Alembic commands ###
